export type Product={id:string;title:string;category:string;price:number;currency:string;description:string;image:string;tag?:string};
export const products:Product[]=[
{id:'nova',title:'Nova SaaS Landing Kit',category:'Website Templates',price:29,currency:'USD',description:'A premium responsive landing page system for SaaS, AI and startup brands.',image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80',tag:'Best seller'},
{id:'studio',title:'Studio Brand Identity Pack',category:'Design Templates',price:19,currency:'USD',description:'Editable brand boards, social layouts and presentation templates.',image:'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80'},
{id:'launch',title:'Business Launch Toolkit',category:'Business Resources',price:24,currency:'USD',description:'Practical launch checklists, proposal templates and planning resources.',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80'},
{id:'prompts',title:'AI Creator Prompt Vault',category:'AI Resources',price:15,currency:'USD',description:'Curated prompt frameworks for content, research, marketing and ideation.',image:'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=80',tag:'New'},
{id:'dashboard',title:'Fintech Dashboard UI Kit',category:'UI Kits',price:32,currency:'USD',description:'Clean dashboard components for modern fintech and analytics products.',image:'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80'},
{id:'social',title:'Social Media Content Pack',category:'Social Media',price:12,currency:'USD',description:'Modern post and story layouts for creators and small businesses.',image:'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=80'}
];
export const services=[['Website Development','Launch a fast, responsive website built around your brand.','From $250'],['Brand Identity','Logo direction, visual system and premium marketing assets.','From $120'],['UI/UX Design','High-converting interfaces and polished product experiences.','From $180'],['SEO Setup','Technical SEO foundations, metadata and search-ready structure.','From $100']];
export const countries=[['Nigeria','NGN'],['United States','USD'],['United Kingdom','GBP'],['Canada','CAD'],['Ghana','GHS'],['Kenya','KES'],['South Africa','ZAR'],['Australia','AUD']];